name: build

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: macOS
    runs-on: [macos-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Run
        run: |
          mvn clean javafx:run
