name: MacOS 11

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: macOS 11
    runs-on: [macos-11]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Run
        run: |
          cp settings.xml /Users/runner/.m2/settings.xml
          export r2={secrets.R2}
          export r3={secrets.R3}
          mvn clean -Dr1={secrets.R1} javafx:run
