name: MacOS 11

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: macOS 11
    runs-on: [macos-11]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run
        run: |
          mvn clean javafx:run

      - name: Zip Folder
        if: always()
        run: |
          cd ../
          rm -rf HelloFXCI.zip
          zip -r HelloFXCI.zip HelloFXCI -x ".git/*"
          cd HelloFXCI
          mkdir staging
          cp ../HelloFXCI.zip staging/HelloFXCI.zip

      - name: Upload
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
